---
- name: Provision
  hosts: all
  become: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/google_compute_engine"

  tasks:
    - name: Set github assignee user
      set_fact:
        github_assignee_user: "{{ lookup('env','INPUT_GITHUB_ASSIGNEE_LOGIN') }}"

    - name: Install packages
      apt:
        name:
          - git
          - python3-pip
          - docker.io
        update_cache: true
      become: true

    - name: Install docker for python
      pip:
        name: docker
        executable: pip3
      become: true

    - name: Create user
      user:
        name: "{{ github_assignee_user }}"
        shell: /bin/bash
        groups: adm,dialout,cdrom,floppy,audio,dip,video,plugdev,netdev,lxd,ubuntu,google-sudoers,docker
        append: true
      become: true
      register: user

    - name: Clone project
      git:
        repo: "https://{{ github_assignee_user }}:{{ lookup('env','INPUT_GITHUB_TOKEN') }}@github.com/{{ lookup('env','GITHUB_REPOSITORY') }}"
        dest: "/home/{{ github_assignee_user }}/{{ lookup('env','GITHUB_REPOSITORY') }}"
        version: "{{ lookup('env','INPUT_BRANCH_NAME') }}"
      ignore_errors: true

    - name: Remove github token
      ini_file:
        path: "/home/{{ github_assignee_user }}/{{ lookup('env','GITHUB_REPOSITORY') }}/.git/config"
        section: 'remote "origin"'
        option: url
        value: "https://github.com/{{ lookup('env','GITHUB_REPOSITORY') }}"

    - name: Change owner
      file:
        path: "/home/{{ github_assignee_user }}/"
        owner: "{{ github_assignee_user }}"
        recurse: yes

    - name: Execute code-serve
      docker_container:
        name: code-server
        image: codercom/code-server:latest
        volumes:
          - "/home/{{ github_assignee_user }}/{{ lookup('env','GITHUB_REPOSITORY') }}:/home/coder/project"
        ports:
          - 8080:8080
        user: "{{ user.uid }}:{{ user.group }}"
        entrypoint: ["dumb-init", "fixuid", "-q", "/usr/local/bin/code-server", "--auth", "none", "--host", "0.0.0.0", "."]
        restart_policy: always
      become: true
