---
- name: Create instance
  hosts: localhost
  gather_facts: false

  tasks:
    - include_vars: "{{ lookup('env','GITHUB_WORKSPACE') }}/inventory.gcp.yml"

    - name: Terraform apply
      terraform:
        project_path: "create-instance/"
        state: present
        force_init: true
        backend_config:
          bucket: "{{ bucket }}"
          prefix: "{{ instance_name }}"
          credentials: "{{ lookup('env','GITHUB_WORKSPACE') }}/{{ service_account_file }}"
        variables:
          project: "{{ projects | first }}"
          region: "{{ regions | first }}"
          credentials: "{{ lookup('env','GITHUB_WORKSPACE') }}/{{ service_account_file }}"
          instance_name: "{{ instance_name }}"
          zone: "{{ lookup('env','INPUT_ZONE') | omit }}"
          instance_type: "{{ lookup('env','INPUT_INSTANCE_TYPE') | omit }}"
      register: terraform_output
      until: terraform_output is success
      retries: 3
      delay: 5

    - name: Show Terraform output
      debug:
        var: terraform_output
      when: terraform_output.changed
      tags:
        - skip_ansible_lint
        # Tasks that run when changed should likely be handlers

    - meta: refresh_inventory

    - pause:
        minutes: 1
      when: terraform_output.changed

    - name: Updating instance ssh metadata
      shell: 'gcloud --quiet beta compute --project "{{ projects[0] }}" ssh --zone "{{ terraform_output.outputs.instance_zone.value }}" "{{ instance_name }}" --command="exit"'

- name: Provision
  import_playbook: provision/playbook.yaml
