name: Continuous testing
on:
  push:

env:
  PROJECT_ID: ${{ secrets.CT_PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  BUCKET: ${{ secrets.CT_BUCKET }}
  SA_KEY: ${{ secrets.CT_SA_KEY }}

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create dev ide in GCP
        uses: ./.github/action
        id: create
        with:
          SA_KEY: ${{ env.SA_KEY }}
          PROJECT: ${{ env.PROJECT_ID }}
          REGION: ${{ env.REGION }}
          BUCKET: ${{ env.BUCKET }}
          BRANCH_NAME: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ASSIGNEE_LOGIN: ${{ github.event.repository.owner.login }}
          PLAYBOOK: /app/playbook.yaml

      - name: Delete dev ide in GCP
        uses: ./.github/action
        id: delete
        with:
          SA_KEY: ${{ secrets.SA_KEY }}
          PROJECT: ${{ secrets.PROJECT }}
          REGION: ${{ secrets.REGION }}
          BUCKET: ${{ secrets.BUCKET }}
          BRANCH_NAME: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLAYBOOK: /app/delete-instance.yaml
